### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by annacarney** [annacarney/cs341_finalproject#1]
# Roadmap

These are the end goals of the project that we have to complete by the end of the semester. Requesting for comment and discussion on this issue for as we further into the project.

- [x] Each program has a name, description, offering period, capacity, and program fee.
- [x] Program fee is different for YMCA member and non-members.
- [ ] The software should be able to
    - [x] Add a program
    - [ ] Search a program
    - [ ] Modify a program
    - [ ] Delete a program
- [ ] The software can should be able to a staff member
    - [ ] Add a staff member
    - [ ] Search a staff member
    - [ ] Modify a staff member
    - [ ] Delete a staff member
- [ ] The software can should be able to a member
    - [ ] Add a member
    - [ ] Search a member
    - [ ] Modify a member
    - [ ] Delete a member
- [x] The program participants can not register/sign up programs with time conflicts
