### ISSUE TITLE
Final Demo Roadmap!

### ISSUE THREAD

**Issue by annacarney** [annacarney/cs341_finalproject#13]
- Staff logs in, searches all the Shark programs in the system, and searches all the program Luke Anderson registered

- Staff cancels the Sunday 5:00 pm Log Rolling

- Admin deletes Jane Doe (inactive/expired)

- Jane Doe can not log into the system any more

- Jane Doe's program registrations are cancelled

- Admin searches Jane Doe

- Show user manual or help

**Comment by annacarney** [comment]
- [x] password hashing --> Ze Jia & Shyue Shi 
- [x] search --> Anna 
- [x] delete person/program from db --> Steven
- [x] User Manual/Help -->  Ze Jia & Shyue Shi

**Comment by annacarney** [comment]
- [x] data validation (for adding program and adding non member)
- [x] implement 'create account'

**Comment by annacarney** [comment]
search nonmembers
