### ISSUE TITLE
Roadmap Demo 1

### ISSUE THREAD

**Issue by annacarney** [annacarney/cs341_finalproject#2]
## Demo 1 

This is what is expected at Demo 1. Check off as completed. 

- [x] The YMCA stafflogs in, set up aswimming program: date, time,  location,description,  price,  andthe number  of participants allowed:Example:  “Shark”, Oct.25,  2020–Dec.  13, Sundays 5:00pm to 5:40pm, YMCA Onalaska pool, maximum 8, $48 member, $96 non-member.Participants must have passedpike levelbefore.
-  [x] Jane  Doe is  a  YMCA  member, logs  in  and  view  the program
-  [x] Luke Anderson is not a YMCA member, view the program offered at this time

**Comment by annacarney** [comment]
To complete all of these we will need the following: 
- [x] Welcome page
- [x] Staff member login
- [x] Member login
- [x] Non-member "login" 
- [x] register a program with date, time, location, description, price, capacity from Staff 
- [x] view programs from member 
- [x] view//SEARCH / register (from times) programs from non-member

**Comment by annacarney** [comment]
Non-member registration for a program --- by name and phone member Do not need to login

staff member and member have same login

**Comment by annacarney** [comment]
need to add a search for the programs (from times)

**Comment by annacarney** [comment]
non member added to database/enrolled in a program: ??
must create a Person with firstname, lastName, phone attr. with un/pass/.. == NULL
add relationship with enroll table to connect the Person to the Program
