### ISSUE TITLE
Demo 2 Roadmap

### ISSUE THREAD

**Issue by annacarney** [annacarney/cs341_finalproject#7]
**DEMO 2**
1. YMCA staff logs in, set up three programs: 
+ “Shark”, Nov. 15, 2020 –Dec. 13, Sundays 5:00pm to 5:40pm, YMCA Onalaska pool, maximum 8, $48 member, $96 non-member. Participants must have passed pike level before.
+ "Shark”, Nov. 15,  2020 –Dec.  13, Mondays&  Wednesdays6:00pm  to 6:40pm, YMCA Onalaska pool, maximum 8, $65member, $130non-member. Participants must have passed pike level before.
+ “Log Rolling”, Nov. 15, 2020 –Dec. 13, Sundays 5:00pm to 5:40pm, YMCA Onalaskapool, maximum 1, $100member, $200non-member. 

2. Jane Doe is a YMCA member, logs in and registers the programs -> Shark at 5:00pm on Sunday and Log Rolling at 5:00pm on Sundays as well.

3. Luke Anderson is not a YMCA member, registers the programs -> Shark on Mondays and Wednesdays at 6:00pm, and Log Rolling on Sundays at 5:00pm.

4. Aini Anderson is a YMCA member, logs in and registers the program -> Log Rolling at 5:00pm on Sundays.

5. Staff views all the program registration.

6. Show    your database    tables(if    you    used    database): Member, Program, Registration...

**Comment by annacarney** [comment]
- [ ] Register member/nonmember for program
    - [ ] deal with program at time conflict

**Comment by annacarney** [comment]
**_Requirements for demo 2:_** 
- [x] Register member/nonmember for program -> Steven ?
- [x] Validation (deal with program at time conflict) -> Shyue Shi / Ze Jia ? 
- [x] Staff view all people registered for program -> Anna ? 

**_Possible things to add if have time:_** 
- [ ] password hashing (more secure like she mentioned in demo 1)

**Comment by annacarney** [comment]
To Fix: 

Validation -- 
- can't register when over capacity
- lets user register for prog1(8:00-9:00, 10-23-2020 to 01-11-2021, Tues Thurs) 
 when already reg for prog2(8:00-9:00, 11-01-2020 to 12-01-2020, Tues Thurs)

**Comment by annacarney** [comment]
Demo time conflict will work

**Comment by annacarney** [comment]
**DEMO 2**

-- YMCA staff logs in, set up three programs:
ID= 6, “Shark”, Size=8, $48 mem $96 nonmem, YMCA Onalaska pool, 11-15-2020 to 12-13-2020, 17:00 to 17:40, Sun
 Participants must have passed pike level before.

ID= 7, "Shark”, Size=8, $65 mem $130 nonmem, YMCA Onalaska pool, 11-15-2020 to 12-13-2020, 18:00 to 18:40, Mon Wed, Participants must have passed pike level before.

ID= 8, “Log Rolling”, Size=1, $100 mem $200 nonmem, YMCA Onalaska pool, 11-15-2020 to 12-13-2020, 17:00 to 17:40, Sun 

-- Jane Doe is a YMCA member, logs in and registers the programs -> Shark at 17:00 on Sunday and Log Rolling at 17:00pm on Sundays as well.

-- Luke Anderson is not a YMCA member, registers the programs -> Shark on Mondays and Wednesdays at 18:00, and Log Rolling on Sundays at 17:00.

-- Aini Anderson is a YMCA member, logs in and registers the program -> Log Rolling at 17:00 on Sundays.

-- Staff views all the program registration.

-- Show your database tables(if you used database): Member, Program, Registration...
